### ISSUE TITLE
Bitflag members are incorrectly identified as an unnamed union

### ISSUE THREAD

**Issue by TrinityDevelopers** [ergrelet/resym#22]
When you have more than one bitflag members, they are incorrectly identified as an unnamed union. For example:
```
struct bitflags {
    bool flag1 : 1;
    bool flag2 : 1;
    bool flag3 : 1;
    bool flag4 : 1;
    bool flag5 : 1;
    bool flag6 : 1;
    bool flag7 : 1;
    bool flag8 : 1;
};
```
Is identified as:
```
struct bitflags {
    union {
        bool flag1 : 1;
        bool flag2 : 1;
        bool flag3 : 1;
        bool flag4 : 1;
        bool flag5 : 1;
        bool flag6 : 1;
        bool flag7 : 1;
        bool flag8 : 1;
    };
};
```

**Comment by ergrelet** [comment]
Hi! Yes indeed, thanks for creating an issue to track this as I forgot to do it!
Bitfields are actually always put inside of a union at the moment (no need to have 8 members). I haven't taken the time to fix this as it shouldn't produce incorrect layouts.

But yes, ideally this should not happen.

**Comment by TrinityDevelopers** [comment]
Yeah I only checked with this one scenario but that would make sense given the implementation. I've updated the issue to reflect.

**Comment by ergrelet** [comment]
The issue should now be fixed on `master`!
