### ISSUE TITLE
Functions that have function pointer return types are not rendered correctly

### ISSUE THREAD

**Issue by TrinityDevelopers** [ergrelet/resym#23]
I know this is a pretty obscure problem since not many functions have function pointer return types that aren't typedef'd, but they do exist and the output ends up incorrect.  For example:
```
struct {
    void (*returns_func_pointer())(int);
};
```
Is rendered as:
```
struct {
    void (* returns_func_pointer();
};
```

**Comment by ergrelet** [comment]
Ah good catch! It might not be widely used indeed but that's a good thing to have this reconstructed properly 😊
