### ISSUE TITLE
error dump struct to union

### ISSUE THREAD

**Issue by inaryart** [ergrelet/resym#34]
- error 1
  - original
  ```C++
  struct Struct1
  {
	  uint16 filed_1 : 1;
	  uint16 filed_2 : 5;
	  uint16 filed_3 : 10;
  };
  ```
  - resym output
  ```
  struct Struct1
  {
	  union {
		  uint16 filed_1 : 1;
		  uint16 filed_2 : 5;
		  uint16 filed_3 : 10;
	  };
  };
  ```

- error 2
  - original
  ```
  union Struct4 {
	  struct
	  {
		  uint16 filed_1 : 1;
		  uint16 filed_2 : 5;
		  uint16 filed_3 : 10;
	  };
  
  };
  ```
  - resym output
  ```
  union Struct4 { /* Size=0x2 */
    /* 0x0000 */ public: uint16_t filed_1 : 1;
    /* 0x0000 */ public: uint16_t filed_2 : 5;
    /* 0x0000 */ public: uint16_t filed_3 : 10;
  };
  ```

they have completely different meanings

[see assembly output here](https://godbolt.org/z/8s9Y7erKn)

**Comment by ergrelet** [comment]
Hi! Thanks for the report.
The first error you mentioned is already tracked by issue #22. The second error is a variant of the same root issue in `resym`.

I'll keep this issue open for tracking progress on the second error 👍

**Comment by ergrelet** [comment]
The issue should now be fixed on `master`!
