### ISSUE TITLE
Parsing causes the console to flicker

### ISSUE THREAD

**Issue by romanholidaypancakes** [ergrelet/resym#43]
step1: load win32k.pdb
step2: load win32kfull.pdb

![resym-x86_64-pc-windows-msvc_IfQLW40ret](https://github.com/ergrelet/resym/assets/51652878/3d73d8d5-340c-4832-8d5c-ed10ca7deac0)

[win32k.zip](https://github.com/ergrelet/resym/files/11953469/win32k.zip)

**Comment by ergrelet** [comment]
Hi!

Thanks for the feedback! 👍
This is indeed a long-standing issue that's quite annoying.
