### ISSUE TITLE
Support for older PDB versions

### ISSUE THREAD

**Issue by tomsons26** [ergrelet/resym#47]
Opening any VS6 made PDB currently throws
`ERROR | Failed to load PDB file: pdb error: Unimplemented PDB feature: small MSF file format`

**Comment by ergrelet** [comment]
Hi!

Yes, unfortunately older PDB files aren't supported by the [pdb](https://github.com/willglynn/pdb) crate so `resym` can't open them. There a couple of old PDBs that I'd like to be able to browse myself.

I see two solutions to get these supported:
- Implement support in the `pdb` crate
  - This might be a bit of work, I'm not sure
- Implement an alternative PDB parsing backend based on the [dia-rs](https://github.com/microsoft/dia-rs) crate in `resym`
  - This wouldn't be portable though (*i.e.*, Windows-only)

**Comment by ergrelet** [comment]
Well it seems someone managed to add support for this without any major modifications: https://github.com/willglynn/pdb/issues/150#issuecomment-1923802296
I should try merging that on the `pdb` fork which is currently in use for resym.

**Comment by ergrelet** [comment]
@tomsons26 You should now be able to open VS6 PDBs from `resym` if you build from the `master` branch or use the web version: https://ergrelet.github.io/resym/
